# Pytorch Tensor Basic Usage<br>


*   Create Tensor
*   Indexing, Joining, Slicing
*   Initialization
*   Math Operations



새 노트에서 런타임 > 런타임 유형 변경 > GPU 지정<br>
새 노트마다 다시 지정해야 함

## 1. Create Tensor

### 1) random numbers
랜덤값을 가지는 텐서 생성 함수들<br>
1. torch.rand() : 0과 1사이의 숫자를 균등하게 생성
2. torch.rand_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서와 동일한 텐서 만들 때 사용
3. torch.randn() : 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해 생성
4. torch.randn_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서를 정의함
5. torch.randint() : 주어진 범위 내의 정수를 균등하게 생성, 자료형은 torch.float32
6. torch.randint_like() : 기존의 텐서를 정의함
7. torch.rendperm() : 주어진 범위 내의 정수를 랜덤하게 생성



In [1]:
# 1. Create Tensor
# 1) random numbers
import torch

# 1. torch.rand(sizes) => 0 ~ 1 사이의 값으로 랜덤값 발생함
# sizes : 1차원 갯수 | 2차원 행렬 갯수 지정
# 0과 1사이의 실수형 숫자를 균등하게 생성
x = torch.rand(2, 3)  # 2행3열로 텐서 생성하고, 랜덤값으로 채움
x

tensor([[0.9013, 0.5098, 0.9030],
        [0.5020, 0.8772, 0.4929]])

In [2]:
# 2. torch.randn(sizes)
# 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해서 랜덤값 생성
x = torch.randn(2, 3)
x

tensor([[-0.2924, -0.1788,  0.8134],
        [ 0.3536,  0.6906,  0.3737]])

In [3]:
# 3. torch.randperm(n) => permutation of 0 ~ n
x = torch.randperm(5)
x

tensor([4, 3, 0, 2, 1])

### 2) zeros, ones, arange

In [4]:
# 2) zeros, ones, arange

# torch.zeros(2, 3) => [[0,0,0],[0,0,0]]
x = torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# torch.ones(2, 3)
x = torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
# torch.arange(start, end, step=1)
x = torch.arange(0, 3, step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

### 3) Tensor Data Type

In [7]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2, 3)
x

tensor([[1.1130e-14, 0.0000e+00, 1.1127e-14],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])

In [8]:
x = torch.FloatTensor([12, 35])
x

tensor([12., 35.])

In [9]:
# torch.type_as(tensor_type)
# 기존의 텐서의 값의 자료형을 바꿀 때 사용
x = x.type_as(torch.IntTensor())
x

tensor([12, 35], dtype=torch.int32)

### 4) Numpy to Tensor, Tensor to Numpy

In [10]:
import numpy as np

# torch.from_numpy(ndarray) => tensor
x1 = np.ndarray(shape=(2, 3), dtype=int, buffer=np.array([1, 2, 3, 4, 5, 6]))
x2 = torch.from_numpy(x1)
x2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# torch.numpy() -> ndarray
x3 = x2.numpy()
x3

array([[1, 2, 3],
       [4, 5, 6]])

### 5) Tensor on CPU & GPU

In [12]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [13]:
x_gpu = x.cuda()
x_gpu

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [14]:
x_cpu = x_gpu.cpu()
x_cpu

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### 6) Tensor Size

In [15]:
# tensor.size() => 인덱스값
x = torch.FloatTensor(10, 12, 3, 3)
x.size()[:]
# x

torch.Size([10, 12, 3, 3])

## 2. Indexing, Slicing, Joining

### 1) Indexing

In [16]:
# torch.index_select(input, dim, index)
# input : 대상 텐서
# dim : 선택할 차원의 인덱스를 지정, 0은 첫번째 차원(행을 의미), 1은 두번째 차원(열을 의미)을 의미함
# index : 선택할 인덱스를 포함한 1차원 텐서를 정의함, [0, 3]은 0번째와 3번째를 의미함
x = torch.rand(4, 3)
out = torch.index_select(x, 0, torch.LongTensor([0, 3]))  # x 텐서에서 0행과 3행 추출
x, out

(tensor([[0.5767, 0.9793, 0.3511],
         [0.0320, 0.0883, 0.3010],
         [0.0223, 0.5040, 0.5094],
         [0.2720, 0.3158, 0.8378]]),
 tensor([[0.5767, 0.9793, 0.3511],
         [0.2720, 0.3158, 0.8378]]))

In [17]:
# 파이썬 indexing 사용 가능
x[:, 0], x[0, :], x[0:2, 0:2]

(tensor([0.5767, 0.0320, 0.0223, 0.2720]),
 tensor([0.5767, 0.9793, 0.3511]),
 tensor([[0.5767, 0.9793],
         [0.0320, 0.0883]]))

In [18]:
# torch.masked_select(input, mask)
x = torch.randn(2, 3)
mask = torch.BoolTensor([[False, False, True], [False, True, False]])
out = torch.masked_select(x, mask)
x, mask, out

(tensor([[ 0.5758, -1.5535, -0.2007],
         [ 2.2770,  1.3668,  0.3455]]),
 tensor([[False, False,  True],
         [False,  True, False]]),
 tensor([-0.2007,  1.3668]))

### 2) Joining

In [19]:
# torch.cat(seq, dim=0|1)
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
y = torch.FloatTensor([[-1, -2, -3], [-4, -5, -6]])

z1 = torch.cat([x, y], dim=0)  # dim=0 (행방향): 아래로 합침
z2 = torch.cat([x, y], dim=1)  # dim=1 (열방향): 오른쪽에 합쳐짐

x, y, z1, z2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.,  2.,  3., -1., -2., -3.],
         [ 4.,  5.,  6., -4., -5., -6.]]))

In [20]:
# torch.stack(sequences, dim=0) => 새로운 차원으로 추가
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])  # shape : (2, 3)
x_stack = torch.stack([x, x, x, x], dim=0)  # shape : (4, 2, 3)
x_stack

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

### 3). Slicing

In [21]:
# torch.chunk(tensor, chunks, dim=0|1)
x_1, x_2 = torch.chunk(z1, 2, dim=0)  # dim=0 : 행들을 2개로 분할
y_1, y_2, y_3 = torch.chunk(z1, 3, dim=1)  # dim=1 : 열들을 3개로 분할

z1, x_1, x_2, y_1, y_2, y_3

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[ 1.],
         [ 4.],
         [-1.],
         [-4.]]),
 tensor([[ 2.],
         [ 5.],
         [-2.],
         [-5.]]),
 tensor([[ 3.],
         [ 6.],
         [-3.],
         [-6.]]))

In [22]:
# torch.split(tensor, split_size, dim=0|1)
x1, x2 = torch.split(z1, 2, dim=0)  # 행으로 2개 분리
y1 = torch.split(z1, 2, dim=1)  # 3개의 열을 2개로 분리

z1, x1, x2, y1

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1., -2., -3.],
         [-4., -5., -6.]]),
 (tensor([[ 1.,  2.],
          [ 4.,  5.],
          [-1., -2.],
          [-4., -5.]]),
  tensor([[ 3.],
          [ 6.],
          [-3.],
          [-6.]])))

### 4) Squeezing

In [23]:
# torch.squeeze(input, dim=None) => 숫자가 1인 차원을 제거
x1 = torch.FloatTensor(10, 1, 3, 4)
# 차원(dimension)의 개념
# 10 : batch size (데이터 한 묶음당 들어있는 데이터(x, y)쌍 갯수)
# 1 : channel size (색상 채널 1은 그레이톤 흑백이미지를 의미함)
# 3 : width image size
# 4 : height image size

x2 = torch.squeeze(x1)

x1.size(), x2.size()

(torch.Size([10, 1, 3, 4]), torch.Size([10, 3, 4]))

In [24]:
# torch.unsqueeze(input, dim=None) => 숫자가 1인 차원을 추가
x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.unsqueeze(x1, dim=0)  # dim=0 이면 첫번째 위치에 추가

x1.size(), x2.size()

(torch.Size([10, 3, 4]), torch.Size([1, 10, 3, 4]))

## 3. Initialization

In [25]:
import torch.nn.init as init

x1 = init.uniform(torch.FloatTensor(3, 4), a=0, b=9)  # a와 b 사이의 값으로 초기화
x2 = init.normal(torch.FloatTensor(3, 4), std=0.2)  # 표준편차 0.2를 적용해서 초기화
x3 = init.constant(torch.FloatTensor(3, 4), 3.145)  # 지정된 상수값으로 초기화

x1, x2, x3

/tmp/ipykernel_644/191971367.py:3: FutureWarning: `nn.init.uniform` is now deprecated in favor of `nn.init.uniform_`.
  x1 = init.uniform(torch.FloatTensor(3, 4), a=0, b=9)  # a와 b 사이의 값으로 초기화
/tmp/ipykernel_644/191971367.py:4: FutureWarning: `nn.init.normal` is now deprecated in favor of `nn.init.normal_`.
  x2 = init.normal(torch.FloatTensor(3, 4), std=0.2)  # 표준편차 0.2를 적용해서 초기화
/tmp/ipykernel_644/191971367.py:5: FutureWarning: `nn.init.constant` is now deprecated in favor of `nn.init.constant_`.
  x3 = init.constant(torch.FloatTensor(3, 4), 3.145)  # 지정된 상수값으로 초기화


(tensor([[2.1424, 2.8409, 1.3078, 3.3023],
         [7.3055, 7.3790, 7.2604, 1.0080],
         [4.4143, 2.8758, 6.5482, 6.0930]]),
 tensor([[ 0.0379, -0.0358,  0.4606, -0.0022],
         [ 0.1886, -0.1646,  0.1416, -0.3357],
         [-0.2854, -0.0025, -0.0924,  0.2522]]),
 tensor([[3.1450, 3.1450, 3.1450, 3.1450],
         [3.1450, 3.1450, 3.1450, 3.1450],
         [3.1450, 3.1450, 3.1450, 3.1450]]))

## 4. Math Operations

### 1) Arithmetic Operations

In [26]:
# torch.add() : 더하기
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
add = torch.add(x1, x2)

x1, x2, add, x1 + x2, x1 - x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [27]:
# torch.add() broadcastion (숫자와의 연산)
x2 = torch.add(x1, 10)

x1, x2, x1 + 10, x2 - 10

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[11., 12., 13.],
         [14., 15., 16.]]),
 tensor([[11., 12., 13.],
         [14., 15., 16.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [28]:
# torch.mul() : 곱하기
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x3 = torch.mul(x1, x2)

x3, x1 * x2

(tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]),
 tensor([[ 1.,  4.,  9.],
         [16., 25., 36.]]))

In [29]:
# torch.mul() broadcastion (숫자와의 연산)
x4 = torch.mul(x1, 10)

x4, x1 * 10

(tensor([[10., 20., 30.],
         [40., 50., 60.]]),
 tensor([[10., 20., 30.],
         [40., 50., 60.]]))

In [30]:
# torch,div() : 나누기 (몫)
x5 = torch.div(x1, 5)

x5, x1 / 5

(tensor([[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]),
 tensor([[0.2000, 0.4000, 0.6000],
         [0.8000, 1.0000, 1.2000]]))

### 2) Other Math Operations

In [31]:
# torch.pow(input, exponent)
x1 = torch.FloatTensor(3, 4)

x1, torch.pow(x1, 2), x1 ** 2

(tensor([[8.7429e-10, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 9.1084e-44, 0.0000e+00],
         [9.0357e-10, 0.0000e+00, 9.0586e-10, 0.0000e+00]]),
 tensor([[7.6438e-19, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [8.1643e-19, 0.0000e+00, 8.2058e-19, 0.0000e+00]]),
 tensor([[7.6438e-19, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [8.1643e-19, 0.0000e+00, 8.2058e-19, 0.0000e+00]]))

In [32]:
# torch.exp(tensor, out=None) : 지수함수
x1 = torch.FloatTensor(3, 4)
out = torch.exp(x1)

x1, out

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [33]:
# torch.log(input, out=None) : 자연로그 계산
out = torch.log(x1)

x1, out

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[-inf, -inf, -inf, -inf],
         [-inf, -inf, -inf, -inf],
         [-inf, -inf, -inf, -inf]]))

### 3) Matrix Operations

In [34]:
# torch.mm(mat1, mat2) => matrix multiplication (행렬곱)
x1 = torch.FloatTensor(3, 4)
x2 = torch.FloatTensor(4, 5)
out = torch.mm(x1, x2)

x1, x2, out

(tensor([[ 9.1009e-10,  0.0000e+00, -1.7048e-07,  4.5042e-41],
         [ 8.9683e-44,  0.0000e+00,  1.1210e-43,  0.0000e+00],
         [ 9.1536e-10,  0.0000e+00,  0.0000e+00,  0.0000e+00]]),
 tensor([[1.2612e-43, 2.8026e-45, 2.8026e-45, 2.8026e-45, 8.9683e-44],
         [0.0000e+00, 4.4842e-44, 0.0000e+00, 4.9168e-14, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.5835e-43],
         [0.0000e+00, 9.0247e-10, 0.0000e+00, 9.0622e-10, 0.0000e+00]]),
 tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]))

In [35]:
# torch.bmm(batch1, batch2) => batch에 대한 행렬곱 연산
# 맨 앞의 batch 는 차원을 유지하면서 뒤 요소들의 행렬곱 연산 수행함

x1 = torch.FloatTensor(10, 3, 4)
x2 = torch.FloatTensor(10, 4, 5)
out = torch.bmm(x1, x2)

out.size()

torch.Size([10, 3, 5])

In [36]:
# torch.dot(tensor1, tensor2) : 백터의 내적을 구함
x1 = torch.FloatTensor([1, 2, 3, 4])
x2 = torch.FloatTensor([2, 3, 4, 5])

torch.dot(x1, x2)

tensor(40.)

In [37]:
# torch.t(matrix) : 텐서의 전치 연산
# 행과 열을 서로 바꿈
x1 = torch.FloatTensor(3, 4)

x1, x1.t(), torch.t(x1)

(tensor([[9.1004e-10, 0.0000e+00, 9.0586e-10, 0.0000e+00],
         [1.1210e-43, 0.0000e+00, 8.9683e-44, 0.0000e+00],
         [9.1607e-10, 0.0000e+00, 9.0550e-10, 0.0000e+00]]),
 tensor([[9.1004e-10, 1.1210e-43, 9.1607e-10],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [9.0586e-10, 8.9683e-44, 9.0550e-10],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]),
 tensor([[9.1004e-10, 1.1210e-43, 9.1607e-10],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [9.0586e-10, 8.9683e-44, 9.0550e-10],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]))

In [38]:
# torch.transpose(input, dim_0, dim_1)
# 바꿀 차원을 2개 지정함 => 텐서의 내부 차원끼리 바꾸기함
x1 = torch.FloatTensor(10, 3, 4)

# 1차원과 2차원을 서로 바꿈
x1.size(), torch.transpose(x1, 1, 2).size(), x1.transpose(1, 2).size()

(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [39]:
# torch.eig(input, eigenvectors=False)
# 고유값(eigen_value), 고유백터(eigen_vector) 로 변환하는 함수
x1 = torch.FloatTensor(4, 4)

# 고유값과 고유백터 계산
x1, torch.linalg.eig(x1)
# 고유값과 고유백터 :
# 어떤 변환(행렬)을 적용했을 때 방향은 변하지 않고 크기만 변하는 특별한 백터와 변화량을 의미함
# 백터(Vector) : 크기 + 방향을 가진 값임
# 예 : (2, 3) 백터는 오른쪽 2, 위쪽 3 방향을 가짐
# 행렬(Matrix) : 백터를 변형시키는 도구
# 예 : 회전, 확대, 축소, 뒤집기 등을 수행
# 예 : [1, 0] -> [2, 0] 크기가 2배 => 고유값은 2임 (고유백터가 얼마나 확대/축소되었는지 나타내는 값)


(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.return_types.linalg_eig(
 eigenvalues=tensor([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]),
 eigenvectors=tensor([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
         [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
         [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
         [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])))